spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/tlias?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tlias      #修改数据库连接地址，默认地址为本机地址，mysql:3306为docker-compose.yml中mysql服务的端口
    username: root
    password: 123456          #docker-compose.yml中mysql服务的密码为123，本机密码为123456


  servlet:
    multipart:
      max-file-size: 10MB   # 文件最大大小
      max-request-size: 100MB   # 文件最大请求大小

mybatis:
  mapper-locations: classpath:mapper/*.xml  #配置mapper文件位置
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #日志输出到控制台
    map-underscore-to-camel-case: true  #驼峰命名规则
server:
  port: 8080  #默认端口为8080

logging:   #日志级别
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug

aliyun:   #阿里云配置,用于文件上传
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucketName: java-webai-1
    region: cn-beijing

wx:   #微信配置
  app-id: wxf2f3ec1435991131  #微信公众号appid
  app-secret: 80cc45346775bb1286bd3b5fa620d81c  #微信公众号appsecret